// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL0Um1YWDUvkXlcMlsI9qMv1yFhFNza8Y',
    appId: '1:342852601914:web:da20556d6d36b688408d03',
    messagingSenderId: '342852601914',
    projectId: 'treecare-69504',
    authDomain: 'treecare-69504.firebaseapp.com',
    storageBucket: 'treecare-69504.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC21N5cEZ22pprJI8idCS4oCk-so3OPOAE',
    appId: '1:342852601914:android:839104b2756baaca408d03',
    messagingSenderId: '342852601914',
    projectId: 'treecare-69504',
    storageBucket: 'treecare-69504.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB88-FyJr_jRnPUaldZwWyQ3jv-mQaETEQ',
    appId: '1:342852601914:ios:6eabb3562a7bb091408d03',
    messagingSenderId: '342852601914',
    projectId: 'treecare-69504',
    storageBucket: 'treecare-69504.firebasestorage.app',
    iosBundleId: 'com.example.a',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB88-FyJr_jRnPUaldZwWyQ3jv-mQaETEQ',
    appId: '1:342852601914:ios:6eabb3562a7bb091408d03',
    messagingSenderId: '342852601914',
    projectId: 'treecare-69504',
    storageBucket: 'treecare-69504.firebasestorage.app',
    iosBundleId: 'com.example.a',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL0Um1YWDUvkXlcMlsI9qMv1yFhFNza8Y',
    appId: '1:342852601914:web:e1e76c114c7c2082408d03',
    messagingSenderId: '342852601914',
    projectId: 'treecare-69504',
    authDomain: 'treecare-69504.firebaseapp.com',
    storageBucket: 'treecare-69504.firebasestorage.app',
  );
}
